/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.garpo.i0007n.view.detailframe;

import com.garpo.i0007n.controll.Controller;
import com.garpo.i0007n.controll.TaskTabelModel;
import com.garpo.i0007n.model.Person;
import com.garpo.i0007n.view.MainFrame;
import com.garpo.i0007n.view.mainframecomponents.TaskTabelPanel;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Anna
 */
public class DetailFrame extends javax.swing.JFrame {

    Controller controller = Controller.getController();
    int id;
    Person assignedTo;
    String cat;
    String status;
    String desc;
    int estTime;
    int usedTime;
    int statusIndex;
    int catIndex;
    int personIndex;
    JTable parent;
    DefaultComboBoxModel statusListModel;
    DefaultComboBoxModel categoryListModel;
    DefaultComboBoxModel personListModel;
    
    public DetailFrame(JTable parent, int id, Person assignedTo, String cat, String status, String desc, int estTime, int usedTime) {
        this.id=id;
        this.assignedTo=assignedTo;
        this.cat=cat;
        this.status = status;
        this.desc = desc;
        this.estTime = estTime;
        this.usedTime = usedTime;
        this.statusListModel = new DefaultComboBoxModel();
        this.categoryListModel = new DefaultComboBoxModel();       
        this.personListModel = new DefaultComboBoxModel(); 
  
        
        
        
         // === Setup Status list ====
        List<String> statusList = controller.getStatusList();
        for(String stats : statusList){
            statusListModel.addElement(stats);
        }
        for(int i = 0; i < statusList.size() ;i++){
            if(statusList.get(i).equals(status)){
                statusIndex = i;
            }
        } 
        
                // === Setup Category Combobox ====

        List<String> categoryList = controller.getCategoryList();
        for(String categoryitem : categoryList){
            categoryListModel.addElement(categoryitem);
        }
        for(int i = 0; i < categoryList.size() ;i++){
            if(categoryList.get(i).equals(cat)){
                catIndex = i;
            }
        } 

        // ==== Setup AssignedTo List ======
        List<Person> persons = controller.getPersons();
        for(Person person : persons){
            personListModel.addElement(person);
        }
        for(int i = 0; i < persons.size() ;i++){
            if(persons.get(i).equals(assignedTo)){
                personIndex = i;
            }
        } 
        
        initComponents();
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetailTaskID = new javax.swing.JLabel();
        lblDetailCategory = new javax.swing.JLabel();
        lblTaskID = new javax.swing.JLabel();
        lblDetailDescription = new javax.swing.JLabel();
        lblDetailStatus = new javax.swing.JLabel();
        lblDetailAssignedTo = new javax.swing.JLabel();
        lblEstimatedTime = new javax.swing.JLabel();
        lblUsedTime = new javax.swing.JLabel();
        txtEstimatedTime = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        cboxAssignedTo = new javax.swing.JComboBox<>();
        txtUsedTime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cboxCategory = new javax.swing.JComboBox<>();
        sepDetailFrame = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDetailTaskID.setText("Ärendenummer:");

        lblDetailCategory.setText("Kategori:");

        lblTaskID.setText(Integer.toString(id));

        lblDetailDescription.setText("Beskrivning:");

        lblDetailStatus.setText("Status:");

        lblDetailAssignedTo.setText("Tilldelad till:");

        lblEstimatedTime.setText("Uppskattad tidsåtgång:");

        lblUsedTime.setText("Verklig tidsåtgång:");

        txtEstimatedTime.setText(Integer.toString(estTime));

        cbStatus.setModel(statusListModel);
        cbStatus.setSelectedIndex(statusIndex);

        cboxAssignedTo.setModel(personListModel);
        cboxAssignedTo.setSelectedIndex(personIndex);

        txtUsedTime.setText(Integer.toString(usedTime));

        txtDescription.setColumns(20);
        txtDescription.setRows(3);
        txtDescription.setText(desc);
        jScrollPane1.setViewportView(txtDescription);

        btnClose.setText("Stäng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnUpdate.setText("Uppdatera");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cboxCategory.setModel(categoryListModel);
        cboxCategory.setSelectedIndex(catIndex);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetailTaskID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTaskID))
                    .addComponent(lblDetailDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetailCategory)
                        .addGap(18, 18, 18)
                        .addComponent(cboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUsedTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtUsedTime))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEstimatedTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEstimatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDetailAssignedTo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxAssignedTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDetailStatus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sepDetailFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetailTaskID)
                    .addComponent(lblTaskID)
                    .addComponent(lblDetailStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetailCategory)
                    .addComponent(lblDetailAssignedTo)
                    .addComponent(cboxAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetailDescription)
                    .addComponent(lblEstimatedTime)
                    .addComponent(txtEstimatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsedTime)
                            .addComponent(txtUsedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose)
                            .addComponent(btnUpdate))))
                .addGap(18, 18, 18)
                .addComponent(sepDetailFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int assigned = cboxAssignedTo.getSelectedIndex();
        int categoryId = cboxCategory.getSelectedIndex();
        int statusId = cbStatus.getSelectedIndex();
        String description = txtDescription.getText();
        int est;
        if(txtEstimatedTime.getText().equals("")){
            est = 0;
        }else{
            est = Integer.parseInt(txtEstimatedTime.getText());
        }
        int used;
        if(txtEstimatedTime.getText().equals("")){
            used = 0;
        }else{
            used = Integer.parseInt(txtUsedTime.getText());
        }
//        int est = Integer.parseInt(txtEstimatedTime.getText()); 
//        int used = Integer.parseInt(txtUsedTime.getText());

            try {
                controller.updateTask(id, assigned+1, categoryId+1, statusId+1, description, est, used);


            } catch (Exception e1) {
                new JOptionPane("Update Error");
                e1.printStackTrace();
            }
        this.dispose();
        //ladda om tabellen i TaskTabelPanel
   //     parent.refresh();
        

        
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cboxAssignedTo;
    private javax.swing.JComboBox<String> cboxCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetailAssignedTo;
    private javax.swing.JLabel lblDetailCategory;
    private javax.swing.JLabel lblDetailDescription;
    private javax.swing.JLabel lblDetailStatus;
    private javax.swing.JLabel lblDetailTaskID;
    private javax.swing.JLabel lblEstimatedTime;
    private javax.swing.JLabel lblTaskID;
    private javax.swing.JLabel lblUsedTime;
    private javax.swing.JSeparator sepDetailFrame;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEstimatedTime;
    private javax.swing.JTextField txtUsedTime;
    // End of variables declaration//GEN-END:variables
}
